# деревья в ширину занимают минимум 4 земли
# не делать землю по типу UUUUUDDDDD, можно только UD

levels = [
    [lambda x: x * 2 / 3, "RRRUDTRRRRRRURRRRRURRRRRRRRRRRURRTRRRRRRRRURRRRRRRRRRRRRRUDDRRRRRRRDRTRRRRRRRRDRTRRRRRRRRRRTRRRRRRRRDRRRRRRTRRRRRRRRTRRRRRRRDRRRRRRRRRURURRRRRRDRDRR"]
]
