# деревья в ширину занимают минимум 4 земли
# не делать землю по типу UUUUUDDDDD, можно только UD

levels = [
    ["TRRRURRRRUURRTRRRRRURRTRRRRRDDRRRRDDRRRRRDTRRRRRR", [(500, 0)], []],
    ["RTRRRRUURRRRURRRRURRRDDRRRRDRTRRRRRDRRRRUUUUTRRRRRDDDDRRRURRRURURURRRRDRRRRDRTRRRRDRRRURRUURUURRRRURURRRURRRURRURRDRRRDDRDTRRRRURRRUR", [(500, 0), (1200, 0), (700, 0)], []],
    ["RRUTRRRRURRURURRURURURRRUTRRRRURRURURRURUUTRRRRUURURRUURURURUURRURURURRURUURRURRURURURRURURURRUTRRRRURRURURRURRRURUURURRRUURURURURURURUUUTRURURURRUURURUURUURRURUURURURURURUURURUURUR", [(500, 0), (1000, -500), (500, -10000)], [(4000, -1000), (-4000, -1000)]],
    ["RRRUUTRRRRURRRDDRRRDTRRRRUURURRDTRRRRUURRURUUUURURUUUTRRRRRRDDRRRDRRRDRDRDRDDDDDDDDDDRRDDDDDDDDDRRDDDDDDDDDRRDDDDDDDDRRDDDDDDDDDDRRDDDDDDDRDDDDDDDDDDRRRDDDDDDDRDDDDDDRRDRDRDDDRDRDRDRDDRRDRDRDRRRDRRRRRUUUURUURUUURURURUUUURUURUURURURRRURUUURURUUUURUURURURUUURURURURURUURURURURURURUURURURURUUTRRRRRRUUURURRRURURURRRRURRRURURURTRRRRDRDRDRDRTRRRRDRDRRUURUURUUURUUURURURURUR", [(500, 0), (0, 0), (2000, 0), (1000, -5000)], [(-500, 0), (2000, -800), (4000, -1000), (3000, -2000), (-4000, 0)]]
]