# деревья в ширину занимают минимум 4 земли
# не делать землю по типу UUUUUDDDDD, можно только UD

levels = [
    ["RRRURRRRUURRRRRRRURRRRRRRDDRRRRDDRRRRRDRRRRRR", [(500, 0)], []],
    ["RRRRRUURRRRURRRRURRRDDRRRRDRRRRRRDRRRRUUUURRRRRDDDDRRRURRRURURURRRRDRRRRDRRRRRDRRRURRUURUURRRRURURRRURRRURRURRDRRRDDRDRRRRURRRUR", [(500, 0), (1200, 0), (700, 0)], []],
    ["RRURRRRURRURURRURURURRRURRRRURRURURRURUURRRRUURURRUURURURUURRURURURRURUURRURRURURURRURURURRURRRRURRURURRURRRURUURURRRUURURURURURURUUURURURURRUURURUURUURRURUURURURURURUURURUURUR", [(500, 0), (1000, -500), (500, -10000)], [(4000, -1000), (-4000, -1000)]],
    ["RRRUURRRRURRRDDRRRDRRRRUURURRDRRRRUURRURUUUURURUUURRRRRRDDRRRDRRRDRDRDRDDDDDDDDDDRDDDDDDDDDRDDDDDDDDDRDDDDDDDDRDDDDDDDDDDRDDDDDDDRDDDDDDDDDDRRRDDDDDDDRDDDDDDRRDRDRDDDRDRDRDRDDRRDRDRDRRRDRRRRRUUUURUURUUURURURUUUURUURUURURURRRURUUURURUUUURUURURURUUURURURURURUURURURURURURUURURURURUURRRRRRUUURURRRURURURRRRURRRURURURRRRRDRDRDRDRRRRRDRDRRUURUURUUURUUURURURURUR", [(500, 0), (0, 0)], [(-500, 0)]]
]